#!/usr/bin/env bash
set -Eeuo pipefail

# Deploy mt5proxy to a stateful GCP Compute Engine VM.
# Run from the mt5proxy repository root, after authenticating gcloud.
#
# Defaults intentionally reuse the Alphard/GCP conventions from the existing ops scripts:
#   - service account: alphard-trader-sa
#   - Artifact Registry repo: alphard
#   - mt5proxy VM name/tag/image name: mt5proxy
#   - API firewall: allow Alphard runner tag -> mt5proxy tag on tcp/8000
#
# Typical usage:
#   gcloud config set project YOUR_PROJECT
#   ./scripts/gcp/deploy_mt5proxy_gcp.sh
#
# With an existing env file containing MT5_LOGIN/MT5_PASSWORD/MT5_SERVER, etc.:
#   MT5_PROXY_ENV_FILE=.env.gcp ./scripts/gcp/deploy_mt5proxy_gcp.sh

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [[ -d "${SCRIPT_DIR}/../.." && -f "${SCRIPT_DIR}/../../Dockerfile" ]]; then
  REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
else
  REPO_ROOT="$(pwd)"
fi
cd "${REPO_ROOT}"

PROJECT_ID="${PROJECT_ID:-$(gcloud config get-value project 2>/dev/null || true)}"
REGION="${REGION:-us-central1}"
ZONE="${ZONE:-us-central1-a}"
NETWORK="${NETWORK:-default}"

# Reuse the existing Alphard service account and Artifact Registry repo by default.
SERVICE_ACCOUNT_NAME="${SA_NAME:-alphard-trader-sa}"
SA_DISPLAY_NAME="${SA_DISPLAY_NAME:-Alphard Trader Service Account}"
AR_REPO="${AR_REPO:-alphard}"

# Reuse the mt5proxy name consistently for VM, tag, image, container, and disk.
INSTANCE_NAME="${INSTANCE_NAME:-mt5proxy}"
MACHINE_TYPE="${MACHINE_TYPE:-e2-standard-2}"
BOOT_DISK_SIZE="${BOOT_DISK_SIZE:-10GB}"
STATE_DISK="${STATE_DISK:-mt5proxy-state}"
STATE_DISK_DEVICE="${STATE_DISK_DEVICE:-mt5proxy-state}"
STATE_DISK_SIZE="${STATE_DISK_SIZE:-50GB}"
MT5_PROXY_TAG="${MT5_PROXY_TAG:-mt5proxy}"
ALPHARD_TAG="${ALPHARD_TAG:-alphard-runner}"
IMAGE_NAME="${IMAGE_NAME:-mt5proxy}"
IMAGE_TAG="${IMAGE_TAG:-$(git rev-parse --short HEAD 2>/dev/null || date +%Y%m%d%H%M%S)}"
CONTAINER_NAME="${CONTAINER_NAME:-mt5proxy}"

# Host ports. API binds to all interfaces so Alphard can reach it over the VPC internal IP.
HOST_NOVNC_PORT="${HOST_NOVNC_PORT:-3000}"
HOST_VNC_PORT="${HOST_VNC_PORT:-5900}"
HOST_API_PORT="${HOST_API_PORT:-8000}"
HOST_BRIDGE_PORT="${HOST_BRIDGE_PORT:-8001}"
BIND_NOVNC_ADDR="${BIND_NOVNC_ADDR:-127.0.0.1}"
BIND_VNC_ADDR="${BIND_VNC_ADDR:-127.0.0.1}"
BIND_API_ADDR="${BIND_API_ADDR:-0.0.0.0}"
BIND_BRIDGE_ADDR="${BIND_BRIDGE_ADDR:-127.0.0.1}"

# Firewall behavior.
CREATE_ALPHARD_FIREWALL="${CREATE_ALPHARD_FIREWALL:-true}"
ALPHARD_FIREWALL_RULE="${ALPHARD_FIREWALL_RULE:-allow-mt5proxy-from-alphard}"
EXPOSE_UI_FIREWALL="${EXPOSE_UI_FIREWALL:-false}"
UI_FIREWALL_RULE="${UI_FIREWALL_RULE:-allow-mt5proxy-ui}"
UI_SOURCE_RANGES="${UI_SOURCE_RANGES:-}"

# Container/runtime behavior.
MT5_PROXY_ENV_FILE="${MT5_PROXY_ENV_FILE:-}"
OVERWRITE_ENV="${OVERWRITE_ENV:-false}"
WAIT_FOR_HEALTH="${WAIT_FOR_HEALTH:-true}"
HEALTH_TIMEOUT_SECONDS="${HEALTH_TIMEOUT_SECONDS:-240}"
TRADING_ENABLED="${TRADING_ENABLED:-false}"
MT5_AUTOINSTALL="${MT5_AUTOINSTALL:-true}"
SCREEN_WIDTH="${SCREEN_WIDTH:-1280}"
SCREEN_HEIGHT="${SCREEN_HEIGHT:-900}"
SCREEN_DEPTH="${SCREEN_DEPTH:-24}"

require_cmd() {
  local cmd="$1"
  if ! command -v "$cmd" >/dev/null 2>&1; then
    echo "Missing required command: $cmd" >&2
    exit 2
  fi
}

require_file() {
  local path="$1"
  if [[ ! -f "$path" ]]; then
    echo "Missing required file: $path" >&2
    echo "Run this script from the mt5proxy repo root." >&2
    exit 2
  fi
}

require_dir() {
  local path="$1"
  if [[ ! -d "$path" ]]; then
    echo "Missing required directory: $path" >&2
    echo "Run this script from the mt5proxy repo root." >&2
    exit 2
  fi
}

random_hex() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 24
  elif command -v python3 >/dev/null 2>&1; then
    python3 - <<'PY'
import secrets
print(secrets.token_hex(24))
PY
  else
    date +%s%N | sha256sum | awk '{print $1}'
  fi
}

quote_env_value() {
  # Write a KEY=value friendly representation for .env files.
  # Values generated by this script are safe; user env files are copied verbatim.
  printf '%s' "$1" | sed "s/'/'\\''/g"
}

if [[ -z "${PROJECT_ID}" ]]; then
  echo "Set PROJECT_ID or run: gcloud config set project YOUR_PROJECT" >&2
  exit 2
fi

require_cmd gcloud
require_cmd tar
require_file Dockerfile
require_dir app
require_dir scripts
require_dir tools
require_dir docker
require_file docker/supervisord.conf
require_file scripts/docker-entrypoint.sh
require_file scripts/start-all.sh

if [[ -n "${MT5_PROXY_ENV_FILE}" && ! -f "${MT5_PROXY_ENV_FILE}" ]]; then
  echo "MT5_PROXY_ENV_FILE does not exist: ${MT5_PROXY_ENV_FILE}" >&2
  exit 2
fi

if [[ "${EXPOSE_UI_FIREWALL}" == "true" ]]; then
  if [[ -z "${UI_SOURCE_RANGES}" ]]; then
    echo "EXPOSE_UI_FIREWALL=true requires UI_SOURCE_RANGES, for example: UI_SOURCE_RANGES=YOUR_IP/32" >&2
    exit 2
  fi
  # If the caller opts into direct UI access, bind noVNC/raw VNC beyond localhost.
  BIND_NOVNC_ADDR="${BIND_NOVNC_ADDR_OVERRIDE:-0.0.0.0}"
  BIND_VNC_ADDR="${BIND_VNC_ADDR_OVERRIDE:-0.0.0.0}"
fi

ARTIFACT_REGISTRY_HOST="${REGION}-docker.pkg.dev"
IMAGE_URI="${ARTIFACT_REGISTRY_HOST}/${PROJECT_ID}/${AR_REPO}/${IMAGE_NAME}:${IMAGE_TAG}"
SA_EMAIL="${SERVICE_ACCOUNT_NAME}@${PROJECT_ID}.iam.gserviceaccount.com"

echo "Using project:        ${PROJECT_ID}"
echo "Using zone:           ${ZONE}"
echo "Using VM name/tag:    ${INSTANCE_NAME} / ${MT5_PROXY_TAG}"
echo "Using image:          ${IMAGE_URI}"
echo "Using service acct:   ${SA_EMAIL}"
echo

gcloud config set project "${PROJECT_ID}" >/dev/null

echo "Enabling required GCP APIs..."
gcloud services enable \
  compute.googleapis.com \
  artifactregistry.googleapis.com \
  cloudbuild.googleapis.com \
  iam.googleapis.com \
  --project "${PROJECT_ID}" >/dev/null

if ! gcloud iam service-accounts describe "${SA_EMAIL}" --project "${PROJECT_ID}" >/dev/null 2>&1; then
  echo "Creating service account: ${SA_EMAIL}"
  gcloud iam service-accounts create "${SERVICE_ACCOUNT_NAME}" \
    --project "${PROJECT_ID}" \
    --display-name "${SA_DISPLAY_NAME}"
else
  echo "Service account exists: ${SA_EMAIL}"
fi

if ! gcloud artifacts repositories describe "${AR_REPO}" --location "${REGION}" --project "${PROJECT_ID}" >/dev/null 2>&1; then
  echo "Creating Artifact Registry repo: ${AR_REPO}"
  gcloud artifacts repositories create "${AR_REPO}" \
    --project "${PROJECT_ID}" \
    --repository-format docker \
    --location "${REGION}" \
    --description "Docker images for Alphard and mt5proxy"
else
  echo "Artifact Registry repo exists: ${AR_REPO}"
fi

# Let the VM pull the image.
gcloud artifacts repositories add-iam-policy-binding "${AR_REPO}" \
  --project "${PROJECT_ID}" \
  --location "${REGION}" \
  --member "serviceAccount:${SA_EMAIL}" \
  --role "roles/artifactregistry.reader" \
  --quiet >/dev/null

echo "Building and pushing mt5proxy image with Cloud Build..."
gcloud builds submit --project "${PROJECT_ID}" --tag "${IMAGE_URI}" .

if ! gcloud compute disks describe "${STATE_DISK}" --zone "${ZONE}" --project "${PROJECT_ID}" >/dev/null 2>&1; then
  echo "Creating persistent state disk: ${STATE_DISK} (${STATE_DISK_SIZE})"
  gcloud compute disks create "${STATE_DISK}" \
    --project "${PROJECT_ID}" \
    --zone "${ZONE}" \
    --size "${STATE_DISK_SIZE}" \
    --type pd-balanced
else
  echo "State disk exists: ${STATE_DISK}"
fi

if ! gcloud compute instances describe "${INSTANCE_NAME}" --zone "${ZONE}" --project "${PROJECT_ID}" >/dev/null 2>&1; then
  echo "Creating VM: ${INSTANCE_NAME}"
  gcloud compute instances create "${INSTANCE_NAME}" \
    --project "${PROJECT_ID}" \
    --zone "${ZONE}" \
    --machine-type "${MACHINE_TYPE}" \
    --image-family debian-12 \
    --image-project debian-cloud \
    --boot-disk-size "${BOOT_DISK_SIZE}" \
    --service-account "${SA_EMAIL}" \
    --scopes cloud-platform \
    --tags "${MT5_PROXY_TAG}" \
    --metadata enable-oslogin=TRUE \
    --disk "name=${STATE_DISK},device-name=${STATE_DISK_DEVICE},mode=rw,boot=no,auto-delete=no"
else
  echo "VM exists: ${INSTANCE_NAME}; updating tags, disk attachment, files, and service."
  gcloud compute instances add-tags "${INSTANCE_NAME}" \
    --project "${PROJECT_ID}" \
    --zone "${ZONE}" \
    --tags "${MT5_PROXY_TAG}" >/dev/null || true

  if ! gcloud compute instances describe "${INSTANCE_NAME}" \
      --project "${PROJECT_ID}" \
      --zone "${ZONE}" \
      --format='value(disks[].deviceName)' | tr ' ;,' '\n' | grep -qx "${STATE_DISK_DEVICE}"; then
    echo "Attaching state disk ${STATE_DISK} to existing VM."
    gcloud compute instances attach-disk "${INSTANCE_NAME}" \
      --project "${PROJECT_ID}" \
      --zone "${ZONE}" \
      --disk "${STATE_DISK}" \
      --device-name "${STATE_DISK_DEVICE}" \
      --mode rw
  fi
fi

if [[ "${CREATE_ALPHARD_FIREWALL}" == "true" ]]; then
  if gcloud compute firewall-rules describe "${ALPHARD_FIREWALL_RULE}" --project "${PROJECT_ID}" >/dev/null 2>&1; then
    echo "Firewall rule exists: ${ALPHARD_FIREWALL_RULE}"
  else
    echo "Creating firewall rule: ${ALPHARD_FIREWALL_RULE}"
    gcloud compute firewall-rules create "${ALPHARD_FIREWALL_RULE}" \
      --project "${PROJECT_ID}" \
      --network "${NETWORK}" \
      --direction INGRESS \
      --action ALLOW \
      --rules "tcp:${HOST_API_PORT}" \
      --source-tags "${ALPHARD_TAG}" \
      --target-tags "${MT5_PROXY_TAG}" \
      --description "Allow Alphard runner VMs to reach MT5 proxy over the VPC internal IP"
  fi
fi

if [[ "${EXPOSE_UI_FIREWALL}" == "true" ]]; then
  if gcloud compute firewall-rules describe "${UI_FIREWALL_RULE}" --project "${PROJECT_ID}" >/dev/null 2>&1; then
    echo "Firewall rule exists: ${UI_FIREWALL_RULE}"
  else
    echo "Creating UI firewall rule: ${UI_FIREWALL_RULE}"
    gcloud compute firewall-rules create "${UI_FIREWALL_RULE}" \
      --project "${PROJECT_ID}" \
      --network "${NETWORK}" \
      --direction INGRESS \
      --action ALLOW \
      --rules "tcp:${HOST_NOVNC_PORT},tcp:${HOST_VNC_PORT}" \
      --source-ranges "${UI_SOURCE_RANGES}" \
      --target-tags "${MT5_PROXY_TAG}" \
      --description "Allow restricted noVNC/raw VNC access to mt5proxy"
  fi
fi

TMPDIR="$(mktemp -d)"
ARCHIVE="$(mktemp -t mt5proxy-gcp.XXXXXX.tgz)"
trap 'rm -rf "${TMPDIR}" "${ARCHIVE}"' EXIT

mkdir -p "${TMPDIR}/etc/mt5proxy" "${TMPDIR}/opt/mt5proxy/bin"

cat > "${TMPDIR}/etc/mt5proxy/runtime.env" <<EOF
MT5PROXY_IMAGE=${IMAGE_URI}
MT5PROXY_ARTIFACT_REGISTRY_HOST=${ARTIFACT_REGISTRY_HOST}
MT5PROXY_CONTAINER_NAME=${CONTAINER_NAME}
MT5PROXY_STATE_DIR=/var/lib/mt5proxy
MT5PROXY_STATE_DISK_DEVICE=${STATE_DISK_DEVICE}
MT5PROXY_BIND_NOVNC_ADDR=${BIND_NOVNC_ADDR}
MT5PROXY_BIND_VNC_ADDR=${BIND_VNC_ADDR}
MT5PROXY_BIND_API_ADDR=${BIND_API_ADDR}
MT5PROXY_BIND_BRIDGE_ADDR=${BIND_BRIDGE_ADDR}
MT5PROXY_HOST_NOVNC_PORT=${HOST_NOVNC_PORT}
MT5PROXY_HOST_VNC_PORT=${HOST_VNC_PORT}
MT5PROXY_HOST_API_PORT=${HOST_API_PORT}
MT5PROXY_HOST_BRIDGE_PORT=${HOST_BRIDGE_PORT}
MT5PROXY_WAIT_FOR_HEALTH=${WAIT_FOR_HEALTH}
MT5PROXY_HEALTH_TIMEOUT_SECONDS=${HEALTH_TIMEOUT_SECONDS}
EOF

GENERATED_API_KEY="${API_KEY:-$(random_hex)}"
GENERATED_VNC_PASSWORD="${VNC_PASSWORD:-$(random_hex)}"

cat > "${TMPDIR}/etc/mt5proxy/container.env.generated" <<EOF
API_KEY=$(quote_env_value "${GENERATED_API_KEY}")
TRADING_ENABLED=$(quote_env_value "${TRADING_ENABLED}")
DISPLAY=:99
SCREEN_WIDTH=$(quote_env_value "${SCREEN_WIDTH}")
SCREEN_HEIGHT=$(quote_env_value "${SCREEN_HEIGHT}")
SCREEN_DEPTH=$(quote_env_value "${SCREEN_DEPTH}")
VNC_PASSWORD=$(quote_env_value "${GENERATED_VNC_PASSWORD}")
VNC_PORT=5900
NOVNC_PORT=6080
WINEPREFIX=/config/.wine
WINEARCH=win64
WINEDEBUG=-all
LIBGL_ALWAYS_SOFTWARE=1
MESA_LOADER_DRIVER_OVERRIDE=llvmpipe
WINEDLLOVERRIDES=mscoree=d;mshtml=d;winemenubuilder.exe=d
MT5_AUTOINSTALL=$(quote_env_value "${MT5_AUTOINSTALL}")
MT5_SETUP_URL=https://download.mql5.com/cdn/web/metaquotes.software.corp/mt5/mt5setup.exe
MT5_FILE=/config/.wine/drive_c/Program Files/MetaTrader 5/terminal64.exe
MT5_CMD_OPTIONS=${MT5_CMD_OPTIONS:-}
MT5LINUX_HOST=127.0.0.1
MT5LINUX_PORT=8001
MT5LINUX_TIMEOUT=${MT5LINUX_TIMEOUT:-300}
MT5_TIMEOUT_MS=${MT5_TIMEOUT_MS:-60000}
READY_MT5_TIMEOUT_MS=${READY_MT5_TIMEOUT_MS:-15000}
BRIDGE_INIT_RETRY_SECONDS=${BRIDGE_INIT_RETRY_SECONDS:-60}
BRIDGE_INIT_TIMEOUT_SECONDS=${BRIDGE_INIT_TIMEOUT_SECONDS:-120}
MT5_LOGIN=${MT5_LOGIN:-}
MT5_PASSWORD=${MT5_PASSWORD:-}
MT5_SERVER=${MT5_SERVER:-}
MT5_TEST_SYMBOL=${MT5_TEST_SYMBOL:-EURUSD}
MT5_TEST_VOLUME=${MT5_TEST_VOLUME:-0.01}
EOF

if [[ -n "${MT5_PROXY_ENV_FILE}" ]]; then
  {
    echo
    echo "# Overrides from ${MT5_PROXY_ENV_FILE}"
    cat "${MT5_PROXY_ENV_FILE}"
  } >> "${TMPDIR}/etc/mt5proxy/container.env.generated"
fi
chmod 0600 "${TMPDIR}/etc/mt5proxy/container.env.generated"

cat > "${TMPDIR}/opt/mt5proxy/bin/run-mt5proxy-container.sh" <<'EOF'
#!/usr/bin/env bash
set -Eeuo pipefail

source /etc/mt5proxy/runtime.env

: "${MT5PROXY_IMAGE:?MT5PROXY_IMAGE is required}"
: "${MT5PROXY_CONTAINER_NAME:=mt5proxy}"
: "${MT5PROXY_STATE_DIR:=/var/lib/mt5proxy}"
: "${MT5PROXY_BIND_NOVNC_ADDR:=127.0.0.1}"
: "${MT5PROXY_BIND_VNC_ADDR:=127.0.0.1}"
: "${MT5PROXY_BIND_API_ADDR:=0.0.0.0}"
: "${MT5PROXY_BIND_BRIDGE_ADDR:=127.0.0.1}"
: "${MT5PROXY_HOST_NOVNC_PORT:=3000}"
: "${MT5PROXY_HOST_VNC_PORT:=5900}"
: "${MT5PROXY_HOST_API_PORT:=8000}"
: "${MT5PROXY_HOST_BRIDGE_PORT:=8001}"

mkdir -p "${MT5PROXY_STATE_DIR}/config" "${MT5PROXY_STATE_DIR}/logs"

exec /usr/bin/docker run \
  --name "${MT5PROXY_CONTAINER_NAME}" \
  --init \
  --rm \
  --shm-size=1g \
  --security-opt seccomp=unconfined \
  --env-file /etc/mt5proxy/container.env \
  -p "${MT5PROXY_BIND_NOVNC_ADDR}:${MT5PROXY_HOST_NOVNC_PORT}:6080" \
  -p "${MT5PROXY_BIND_VNC_ADDR}:${MT5PROXY_HOST_VNC_PORT}:5900" \
  -p "${MT5PROXY_BIND_API_ADDR}:${MT5PROXY_HOST_API_PORT}:8000" \
  -p "${MT5PROXY_BIND_BRIDGE_ADDR}:${MT5PROXY_HOST_BRIDGE_PORT}:8001" \
  -v "${MT5PROXY_STATE_DIR}/config:/config" \
  -v "${MT5PROXY_STATE_DIR}/logs:/logs" \
  "${MT5PROXY_IMAGE}"
EOF
chmod 0755 "${TMPDIR}/opt/mt5proxy/bin/run-mt5proxy-container.sh"

cat > "${TMPDIR}/opt/mt5proxy/bin/install-mt5proxy-vm.sh" <<'EOF'
#!/usr/bin/env bash
set -Eeuo pipefail

PAYLOAD_DIR="${PAYLOAD_DIR:-/tmp/mt5proxy-gcp}"
OVERWRITE_ENV="${OVERWRITE_ENV:-false}"

apt-get update
apt-get install -y ca-certificates curl gnupg docker.io util-linux e2fsprogs jq
systemctl enable --now docker

install -d -m 0755 /opt/mt5proxy/bin /etc/mt5proxy /var/lib/mt5proxy
install -m 0644 "${PAYLOAD_DIR}/etc/mt5proxy/runtime.env" /etc/mt5proxy/runtime.env
install -m 0755 "${PAYLOAD_DIR}/opt/mt5proxy/bin/run-mt5proxy-container.sh" /opt/mt5proxy/bin/run-mt5proxy-container.sh

if [[ ! -f /etc/mt5proxy/container.env || "${OVERWRITE_ENV}" == "true" ]]; then
  install -m 0600 "${PAYLOAD_DIR}/etc/mt5proxy/container.env.generated" /etc/mt5proxy/container.env
else
  echo "Keeping existing /etc/mt5proxy/container.env. Set OVERWRITE_ENV=true to replace secrets/env."
fi

source /etc/mt5proxy/runtime.env

if [[ -n "${MT5PROXY_STATE_DISK_DEVICE:-}" ]]; then
  STATE_DEVICE="/dev/disk/by-id/google-${MT5PROXY_STATE_DISK_DEVICE}"
  if [[ -e "${STATE_DEVICE}" ]]; then
    if ! blkid "${STATE_DEVICE}" >/dev/null 2>&1; then
      echo "Formatting state disk ${STATE_DEVICE} as ext4"
      mkfs.ext4 -F "${STATE_DEVICE}"
    fi
    mkdir -p "${MT5PROXY_STATE_DIR:-/var/lib/mt5proxy}"
    if ! mountpoint -q "${MT5PROXY_STATE_DIR:-/var/lib/mt5proxy}"; then
      mount "${STATE_DEVICE}" "${MT5PROXY_STATE_DIR:-/var/lib/mt5proxy}"
    fi
    if ! grep -qE "^[^#].* ${MT5PROXY_STATE_DIR:-/var/lib/mt5proxy} " /etc/fstab; then
      echo "${STATE_DEVICE} ${MT5PROXY_STATE_DIR:-/var/lib/mt5proxy} ext4 defaults,nofail 0 2" >> /etc/fstab
    fi
  else
    echo "WARNING: state disk device ${STATE_DEVICE} not found; using boot disk path ${MT5PROXY_STATE_DIR:-/var/lib/mt5proxy}" >&2
  fi
fi

mkdir -p "${MT5PROXY_STATE_DIR:-/var/lib/mt5proxy}/config" "${MT5PROXY_STATE_DIR:-/var/lib/mt5proxy}/logs"
chmod 0755 "${MT5PROXY_STATE_DIR:-/var/lib/mt5proxy}"

if ! command -v gcloud >/dev/null 2>&1; then
  apt-get install -y apt-transport-https ca-certificates gnupg curl
  curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg \
    | gpg --dearmor \
    | tee /usr/share/keyrings/cloud.google.gpg >/dev/null
  echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" \
    | tee /etc/apt/sources.list.d/google-cloud-sdk.list >/dev/null
  apt-get update
  apt-get install -y google-cloud-cli
fi

gcloud auth configure-docker "${MT5PROXY_ARTIFACT_REGISTRY_HOST}" --quiet

docker pull "${MT5PROXY_IMAGE}"

cat > /etc/systemd/system/mt5proxy.service <<'UNIT'
[Unit]
Description=MT5 Proxy Docker container
After=docker.service network-online.target
Wants=docker.service network-online.target

[Service]
Type=simple
EnvironmentFile=/etc/mt5proxy/runtime.env
ExecStartPre=-/usr/bin/docker rm -f ${MT5PROXY_CONTAINER_NAME}
ExecStart=/opt/mt5proxy/bin/run-mt5proxy-container.sh
ExecStop=/usr/bin/docker stop ${MT5PROXY_CONTAINER_NAME}
Restart=always
RestartSec=10
TimeoutStartSec=0

[Install]
WantedBy=multi-user.target
UNIT

systemctl daemon-reload
systemctl enable mt5proxy.service
systemctl restart mt5proxy.service

if [[ "${MT5PROXY_WAIT_FOR_HEALTH:-true}" == "true" ]]; then
  deadline=$((SECONDS + ${MT5PROXY_HEALTH_TIMEOUT_SECONDS:-240}))
  until curl -fsS "http://127.0.0.1:${MT5PROXY_HOST_API_PORT:-8000}/health" >/dev/null 2>&1; do
    if (( SECONDS >= deadline )); then
      echo "MT5 proxy health endpoint did not become live yet. Inspect logs with: journalctl -u mt5proxy.service -n 200 --no-pager" >&2
      break
    fi
    sleep 5
  done
fi

systemctl --no-pager --full status mt5proxy.service || true
docker ps --filter "name=${MT5PROXY_CONTAINER_NAME}" || true
EOF
chmod 0755 "${TMPDIR}/opt/mt5proxy/bin/install-mt5proxy-vm.sh"

tar -C "${TMPDIR}" -czf "${ARCHIVE}" .
if ! tar -tzf "${ARCHIVE}" | grep -Eq '(^|\./)opt/mt5proxy/bin/install-mt5proxy-vm\.sh$'; then
  echo "Internal packaging error: missing install script in payload" >&2
  tar -tzf "${ARCHIVE}" >&2
  exit 2
fi

echo "Uploading VM install payload..."
gcloud compute scp "${ARCHIVE}" "${INSTANCE_NAME}:/tmp/mt5proxy-gcp.tgz" \
  --project "${PROJECT_ID}" \
  --zone "${ZONE}"

REMOTE_INSTALL_CMD="$(cat <<EOF
set -Eeuo pipefail
sudo rm -rf /tmp/mt5proxy-gcp
sudo mkdir -p /tmp/mt5proxy-gcp
sudo tar -xzf /tmp/mt5proxy-gcp.tgz -C /tmp/mt5proxy-gcp
sudo env OVERWRITE_ENV=${OVERWRITE_ENV} PAYLOAD_DIR=/tmp/mt5proxy-gcp bash /tmp/mt5proxy-gcp/opt/mt5proxy/bin/install-mt5proxy-vm.sh
EOF
)"

echo "Installing/updating mt5proxy service on VM..."
gcloud compute ssh "${INSTANCE_NAME}" \
  --project "${PROJECT_ID}" \
  --zone "${ZONE}" \
  --command "${REMOTE_INSTALL_CMD}"

INTERNAL_IP="$(gcloud compute instances describe "${INSTANCE_NAME}" \
  --project "${PROJECT_ID}" \
  --zone "${ZONE}" \
  --format='value(networkInterfaces[0].networkIP)')"

EXTERNAL_IP="$(gcloud compute instances describe "${INSTANCE_NAME}" \
  --project "${PROJECT_ID}" \
  --zone "${ZONE}" \
  --format='value(networkInterfaces[0].accessConfigs[0].natIP)' 2>/dev/null || true)"

REMOTE_SECRETS_CMD="sudo awk -F= '/^(API_KEY|VNC_PASSWORD)=/{print}' /etc/mt5proxy/container.env"
REMOTE_SECRETS="$(gcloud compute ssh "${INSTANCE_NAME}" \
  --project "${PROJECT_ID}" \
  --zone "${ZONE}" \
  --command "${REMOTE_SECRETS_CMD}" 2>/dev/null || true)"

REMOTE_API_KEY="$(printf '%s\n' "${REMOTE_SECRETS}" | awk -F= '/^API_KEY=/{print substr($0, index($0,"=")+1)}' | tail -1)"
REMOTE_VNC_PASSWORD="$(printf '%s\n' "${REMOTE_SECRETS}" | awk -F= '/^VNC_PASSWORD=/{print substr($0, index($0,"=")+1)}' | tail -1)"

cat <<EOF

MT5 proxy deployed.

Image:        ${IMAGE_URI}
VM:           ${INSTANCE_NAME} (${MACHINE_TYPE}) in ${ZONE}
Internal URL: http://${INTERNAL_IP}:${HOST_API_PORT}
External IP:  ${EXTERNAL_IP:-none}
API token:    ${REMOTE_API_KEY:-<read /etc/mt5proxy/container.env on VM>}
VNC password: ${REMOTE_VNC_PASSWORD:-<empty or read /etc/mt5proxy/container.env on VM>}
State:        ${STATE_DISK} mounted at /var/lib/mt5proxy
Logs:         /var/lib/mt5proxy/logs and journalctl -u mt5proxy.service

For Alphard .env.cloud:
MT5_BASE_URL=http://${INTERNAL_IP}:${HOST_API_PORT}
MT5_API_KEY=${REMOTE_API_KEY:-<api-token>}

Open the MT5 UI through an SSH tunnel from your laptop:
gcloud compute ssh ${INSTANCE_NAME} --zone ${ZONE} --project ${PROJECT_ID} -- \\
  -L ${HOST_NOVNC_PORT}:127.0.0.1:${HOST_NOVNC_PORT} \\
  -L ${HOST_VNC_PORT}:127.0.0.1:${HOST_VNC_PORT} \\
  -L ${HOST_API_PORT}:127.0.0.1:${HOST_API_PORT}

Then open:
noVNC:  http://127.0.0.1:${HOST_NOVNC_PORT}/vnc.html
API:    http://127.0.0.1:${HOST_API_PORT}/health
Ready:  http://127.0.0.1:${HOST_API_PORT}/health/ready
Raw VNC: 127.0.0.1:${HOST_VNC_PORT}

Useful VM checks:
gcloud compute ssh ${INSTANCE_NAME} --zone ${ZONE} --project ${PROJECT_ID} --command 'sudo journalctl -u mt5proxy.service -n 200 --no-pager'
gcloud compute ssh ${INSTANCE_NAME} --zone ${ZONE} --project ${PROJECT_ID} --command 'sudo docker logs --tail 200 mt5proxy'

EOF
